#include "stdio.h"
#include <iostream>
#include <iterator>
#include <list>
#include <memory>

#include "ilic/capi.h"
#include "../abi/Json.h"
#include "../util/os.h"
#include "../util/StringMap.h"
#include "../util/StringUtil.h"
#include "../util/Logger.h"
#include "../util/IliFile.h"
#include "../core/CompilerContext.h"

#include "../input/ili1/Ili1Input.h"
#include "../input/ili2/Ili2Input.h"
#include "../input/ili2/InterlisModel.h"

#include "../metamodel/SemanticChecker.h"
#include "../metamodel/TranslationChecker.h"

#include "../output/Ili1Output.h"
#include "../output/Ili2Output.h"
#include "../output/ImdOutput.h"
#include "../output/XsdOutput.h"
#include "../output/GmlOutput.h"

#include "ilic.h"
#ifdef ILIC_NATIVE_REPOSITORY
#include "ilic/Repository.h"
#include "RepositoryCli.h"
#endif
//#include "Gui.h"

using namespace std;
using namespace util;
using namespace metamodel;
struct CliState {
   ilic::SourceManager sessionSources;
   ilic::detail::CompilerContext context;
   list<IliFile *> compiledFiles;
   list<string> compiledModels;
   string modelFilter;

   CliState() : context(sessionSources,ilic::CompilerOptions{}) {}
};

static void abort(Logger &logger,int exitcode)
{
   logger.error(DiagnosticId::CompilerInternal,
      "compilation aborted with status " + to_string(exitcode),-1);
}

string get_program_name()
{
   return "ilic";
}

string get_version()
{
   return "0.9.9";
}

string get_version_string()
{
   return get_program_name() + " " + get_version()
      + " (builddate=" + ansi_date_to_ymd(__DATE__) + ", platform=" + get_platform() + ")";
}

static void display_version(Logger &logger) {
	logger.message(get_version_string());
   logger.message("");
   logger.incNestLevel();
	logger.message("Distributed by the Coordination of Geographic Information");
	logger.message("and Geographic Information Systems Group (COSIG), CH-3084 Wabern.");
	logger.message("Developed and maintained by infoGrips GmbH, CH-8005 Zurich.");
	logger.message("See http://www.interlis.ch for information about INTERLIS.");
	logger.message("Parts of this program have been generated by ANTLR; see http://www.antlr.org");
	logger.message("Parts of this program have been taken from the ili2c compiler project.");
   logger.message(get_program_name() + " is free software without any license restrictions. The project is");
   logger.message("maintained on http://github.com/infogrips/ilic.");
   logger.decNestLevel();
}

static void display_description(Logger &logger) {
	logger.message("DESCRIPTION");
   logger.message("");
   logger.incNestLevel();
   logger.message("Compiles INTERLIS Version 1.0, 2.3 and 2.4 data model definitions and validates them.");
   logger.message("ilic can generate output in serveral formats (ili, imd, xsd, gml).");
   logger.decNestLevel();
}

static void display_options(Logger &logger) {

   logger.message("OPTIONS");
   logger.incNestLevel();

   logger.message("");
   logger.message("input options:");
   logger.message("-ilidirs");
   logger.message("   list of directories to search for .ili files separated by semicolons.");
   logger.message("-no_auto|-no-auto");
   logger.message("   don't search automatically for missing models.");
#ifdef ILIC_NATIVE_REPOSITORY
   logger.message("-repositories uri1;uri2");
   logger.message("   ordered local or HTTP(S) INTERLIS model repositories.");
   logger.message("-models model1,model2");
   logger.message("   resolve root models from the configured repositories.");
   logger.message("-ili-version 1.0|2.3|2.4");
   logger.message("   constrain repository lookup to an INTERLIS language version.");
   logger.message("-no-default-repositories");
   logger.message("   use only explicitly configured repositories.");
#endif

   logger.message("");
   logger.message("output options:");
   logger.message("-o1 [ili_file] [-model_filter model_name]");
   logger.message("   generate INTERLIS 1.0 model definition for model model_name.");
   logger.message("-o23 [ili_file] | -o2 [ili_file] [-model_filter model_name]");
   logger.message("   generate INTERLIS 2.3 model definition.");
   logger.message("-o24 [ili_file] [-model_filter model_name]");
   logger.message("   generate INTERLIS 2.4 model definition.");
   logger.message("-oIMD [imd_file]");
   logger.message("   generate IlisMeta07 output.");
   logger.message("-oXSD [xsd_file]");
   logger.message("   generate xml schema for xtf transfer.");
   logger.message("-oGML [gml_file]");
   logger.message("   generate gml schema for transfer.");
   logger.message("-out|-output file (for compatiblity with ili2c compiler only)");
   logger.message("   file for output");

   logger.message("");
   logger.message("log options:");
   logger.message("-log logfile");
   logger.message("   generate log file");
   logger.message("-silent|-quiet");
   logger.message("    suppress all messages.");
   logger.message("-no_info");
   logger.message("   display no info messages.");
   logger.message("-no_warnings|-without-warnings");
   logger.message("   display no warnings.");
   logger.message("-no_errors");
   logger.message("   display no errors.");
   logger.message("-debug");
   logger.message("   display debug messages.");

   logger.message("");
   logger.message("other options:");
   logger.message("--compile-json");
   logger.message("   read one C API compilation request as JSON from stdin and write the result to stdout.");
   logger.message("-h|-help");
   logger.message("    display this help text.");
   logger.message("-u|-usage");
   logger.message("   display short information about usage.");
   logger.message("-v|-version");
   logger.message("   display the version of ili2c.");
   logger.message("-werror");
   logger.message("   treat warnings as errors.");
   logger.message("-success success_status");
   logger.message("   return status success_status, if no errors detected (default: 0).");
   logger.message("-indent spaces");
   logger.message("   number of ident spaces for output formats.");

   logger.decNestLevel();

}

static bool is_compile_json_request_error(const string &result)
{
   try {
      const ilic::json::Value json = ilic::json::parse(result);
      if (!json.get("diagnostics").isArray()) return true;
      for (const auto &diagnostic : json.get("diagnostics").array()) {
         if (diagnostic.get("code").isString() &&
            diagnostic.get("code").string() == "ILIC-ABI-REQUEST") return true;
      }
      return false;
   }
   catch (...) {
      return true;
   }
}

static int compile_json()
{
   const string request((istreambuf_iterator<char>(cin)),istreambuf_iterator<char>());
   if (cin.bad()) {
      cerr << "ilic: failed to read compilation request from stdin" << endl;
      return 2;
   }

   const uint32_t session = ilic_session_create();
   if (session == 0) {
      cerr << "ilic: failed to create compiler session" << endl;
      return 2;
   }
   const uint32_t result = ilic_compile(session,request.data(),request.size());
   ilic_session_destroy(session);

   size_t result_length = 0;
   const char *result_json = ilic_result_json(result,&result_length);
   if (result_json == nullptr) {
      cerr << "ilic: compiler did not return a JSON result" << endl;
      ilic_result_destroy(result);
      return 2;
   }
   const string output(result_json,result_length);
   ilic_result_destroy(result);
   cout << output << endl;
   return is_compile_json_request_error(output) ? 2 : 0;
}

static void display_usage(Logger &logger) {
   logger.message("USAGE");
   logger.message("");
   logger.incNestLevel();
   logger.message(get_program_name() + " [options] file1.ili file2.ili ...");
   logger.decNestLevel();
}

static void display_examples(Logger &logger) {
	logger.message("EXAMPLES");
   logger.incNestLevel();
   logger.message("");
	logger.message("check whether INTERLIS definition in \"file.ili\" is valid:");
	logger.message("   " + get_program_name() + " file.ili");
	logger.message("");
	logger.message("check whether definitions distributed over several files are valid:");
	logger.message("   " + get_program_name() + " file1.ili file2.ili");
   logger.message("");
   logger.message("generate INTERLIS 1 model definition:");
   logger.message("   " + get_program_name() + " -o1 file1.ili file.ili");
   logger.message("");
   logger.message("generate INTERLIS 2.4 model definition:");
   logger.message("   " + get_program_name() + " -o24 file24.ili file.ili");
   logger.message("");
   logger.message("generate INTERLIS metamodel format:");
   logger.message("   " + get_program_name() + " -oIMD file.imd file1.ili file2.ili");
   logger.message("");
   logger.message("generate XML-Schema:");
   logger.message("   " + get_program_name() + " -oXSD file.xsd file1.ili file2.ili");
   logger.message("");
   logger.message("generate INTERLIS meta format and XML-Schema:");
   logger.message("   " + get_program_name() + " -oIMD file.imd -oXSD file.xsd file1.ili file2.ili");
   logger.decNestLevel();
}

static void display_help(Logger &logger) {
   logger.message("");
   display_version(logger);
   logger.message("");
   display_description(logger);
   logger.message("");
   display_usage(logger);
   logger.message("");
   display_options(logger);
   logger.message("");
   display_examples(logger);
}

StringMap parse_arguments(int argc, char* argv[])
{

   StringMap arguments;
   string key = "";
   string value = "";
   int fid = 1;

   for (int i=1;i<argc;i++) {
      string arg = argv[i];
      if (arg.find("--") == 0) {
         key = arg.substr(2);
      }
      else if (arg.find("-") == 0) {
         key = arg.substr(1);
      }
      else if (ends_with(arg,".ili")) {
         if (key != "o1" && key != "o23" && key != "o24") {
            key = "ilifile" + to_string(fid++);
         }
         value = arg;
      }
      else {
         value = arg;
      }
      if (key != "") {
         if (key == "o2") {
            key = "o23";
         }
         else if (key == "out") {
            key = "output";
         }
         else if (key == "v") {
            key = "version";
         }
         else if (key == "u") {
            key = "usage";
         }
         else if (key == "h") {
            key = "help";
         }
         else if (key == "quiet") {
            key = "silent";
         }
         else if (arg == "without-warnings") {
            key = "no_warnings";
         }
         else if (arg == "no-auto") {
            key = "no_auto";
         }
         arguments.put(key,value);
         value = "";
      }
   }

   return arguments;

}

static void check_arguments(StringMap arguments,Logger &logger)
{

   if (arguments.size() == 0) {
      display_help(logger);
		exit(0);
	}

   for (auto arg : arguments.getKeys()) {
      if (arg == "no_auto") {
         continue;
      }
      else if (arg == "o1") {
         continue;
      }
      else if (arg == "o23") {
         continue;
      }
      else if (arg == "o24") {
         continue;
      }
      else if (arg == "oXSD") {
         continue;
      }
      else if (arg == "oGML") {
         continue;
      }
      else if (arg == "oIMD") {
         continue;
      }
      else if (arg == "output") {
         continue;
      }
      else if (arg == "ilidirs") {
         continue;
      }
      else if (arg == "repositories" || arg == "models" || arg == "ili-version"
         || arg == "no-default-repositories") {
         continue;
      }
      else if (arg == "silent") {
         continue;
      }
      else if (arg == "no_info") {
         continue;
      }
      else if (arg == "no_warnings") {
         continue;
      }
      else if (arg == "no_errors") {
         continue;
      }
      else if (arg == "debug") {
         continue;
      }
      else if (arg == "help") {
         continue;
      }
      else if (arg == "usage") {
         continue;
      }
      else if (arg == "version") {
         continue;
      }
      else if (arg == "log") {
         continue;
      }
      else if (arg.find("ilifile") == 0) {
         continue;
      }
      else if (arg.find("gui") == 0) {
         continue;
      }
      else if (arg.find("state.modelFilter") == 0) {
         continue;
      }
      else if (arg == "werror") {
         continue;
      }
      else if (arg == "success") {
         continue;
      }
      else if (arg == "ident") {
         continue;
      }
      else {
         logger.error("unknown argument -" + arg + "/--" + arg);
         abort(logger,1);
      }
   }

}

static bool compile(CliState &state,IliFile *f)
{
   Logger &logger = state.context.logger();

   if (f->getIliVersion() == "1.0") {
   }
   else if (f->getIliVersion() == "2.3") {
   }
   else if (f->getIliVersion() == "2.4") {
   }
   else {
      logger.error(f->getFilePath() + ": unsupported iliversion " + f->getIliVersion());
      logger.decNestLevel();
      abort(logger,1);
   }

   for (auto ff : state.compiledFiles) {
      if (ff == f) {
         return true;
      }
   }

   // verify if all imported models are in the same file or already compiled
   for (auto import : f->getRequiredModels()) {
      bool found = false;
      // search in same file
      for (auto model : f->getModels()) {
         if (model == import) {
            found = true;
            break;
         }
      }

      for (auto model : f->getModels()) {
         if (model == import) {
            found = true;
            break;
         }
      }

      if (!found) {
         // search in already compiled files
         for (auto model : state.compiledModels) {
            if (model == import) {
               found = true;
               break;
            }
         }
      }
      if (!found) {
         bool translationBase = false;
         for (const auto &translation : f->getTranslationModels()) {
            if (translation == import) {
               translationBase = true;
               break;
            }
         }
         if (!translationBase) return false; // not ready to compile f
      }
   }

   logger.info("");
   logger.info("compiling " + f->getFilePath() + " ...");
   logger.incNestLevel();
   int errors = logger.getErrorCount();

   // parse input
   if (f->getIliVersion() == "1.0") {
      const string source = f->source().text;
      input::parseIli1({f->getFilePath(),source,0},state.context.builder(),logger);
   }
   else {
      const string source = f->source().text;
      input::parseIli2({f->getFilePath(),source,0},state.context.builder(),logger);
   }

   state.compiledFiles.push_back(f);
   if (f->getFilePath() == "INTERLIS") {
      state.compiledModels.push_back("INTERLIS");
   }
   else {
      for (auto model : f->getModels()) {
         state.compiledModels.push_back(model);
      }
   }

   logger.decNestLevel();
   if (logger.getErrorCount() == errors) {
      logger.info(f->getFilePath() + " compiled.");
   }
   else {
      logger.info(f->getFilePath() + " compiled with errors.");
   }

   return true;

}

static void generate_ili1(CliState &state,string ili1_file,Model *m)
{
   Logger &logger = state.context.logger();
   logger.info("");
   logger.info("generating " + ili1_file + ", model=" + m->Name + " ...");
   logger.incNestLevel();
   output::Ili1Output ili1output(state.context.models(),logger,ili1_file);
   ili1output.visit(m);
   logger.decNestLevel();
   logger.info("done.");
}

static void generate_ili23(CliState &state,string ili23_file)
{
   Logger &logger = state.context.logger();
   logger.info("");
   logger.info("generating " + ili23_file + " ...");
   logger.incNestLevel();
   output::Ili2Output ili23output(state.context.models(),logger,ili23_file,"2.3");
   if (state.modelFilter == "") {
      ili23output.visitAllModels();
   }
   else {
      ili23output.preVisit();
      for (auto m : state.context.models().models()) {
         if (m->Name == state.modelFilter) {
            ili23output.visit(m);
         }
      }
      ili23output.postVisit();
   }
   logger.decNestLevel();
   logger.info("done.");
}

static void generate_ili24(CliState &state,string ili24_file)
{
   Logger &logger = state.context.logger();
   logger.info("");
   logger.info("generating " + ili24_file + " ...");
   logger.incNestLevel();
   output::Ili2Output ili24output(state.context.models(),logger,ili24_file, "2.4");
   if (state.modelFilter == "") {
      ili24output.visitAllModels();
   }
   else {
      ili24output.preVisit();
      for (auto m : state.context.models().models()) {
         if (m->Name == state.modelFilter) {
            ili24output.visit(m);
         }
      }
      ili24output.postVisit();
   }
   logger.decNestLevel();
   logger.info("done.");
}

static void generate_imd(CliState &state,string imd_file,string iliversion)
{
   Logger &logger = state.context.logger();
   logger.info("");
   logger.info("generating " + imd_file + " ...");
   logger.incNestLevel();
   output::ImdOutput imdoutput(state.context.models(),logger,imd_file,iliversion);
   imdoutput.visitAllModels();
   logger.decNestLevel();
   logger.info("done.");
}

static void generate_xsd(CliState &state,string xsd_file,string iliversion)
{
   Logger &logger = state.context.logger();
   logger.info("");
   logger.info("generating " + xsd_file + " ...");
   logger.incNestLevel();
   output::XsdOutput xsdoutput(state.context.models(),logger,xsd_file,iliversion,get_version());
   xsdoutput.visitAllModels();
   logger.decNestLevel();
   logger.info("done.");
}

static void generate_gml(CliState &state,string gml_file,string iliversion)
{
   Logger &logger = state.context.logger();
   logger.info("");
   logger.info("generating " + gml_file + " ...");
   logger.incNestLevel();
   output::GmlOutput gmloutput(state.context.models(),logger,gml_file,iliversion,get_version());
   gmloutput.visitAllModels();
   logger.decNestLevel();
   logger.info("done.");
}

int main(int argc, char* argv[])
{

   if (argc >= 2 && string(argv[1]) == "--compile-json") {
      if (argc != 2) {
         cerr << "ilic: --compile-json does not accept additional arguments" << endl;
         return 2;
      }
      return compile_json();
   }

   CliState state;
   Logger &logger = state.context.logger();

   StringMap arguments = parse_arguments(argc,argv);
   check_arguments(arguments,logger);
   bool help = false;
   bool usage = false;
   bool version = false;
   bool no_auto = false;
   string output = "";
   bool ili1 = false;
   string ili1_output = "interlis1.ili";
   bool ili23 = false;
   string ili23_output = "interlis23.ili";
   bool ili24 = false;
   string ili24_output = "interlis24.ili";
   bool imd = false;
   string imd_output = "output.imd";
   bool xsd = false;
   string xsd_output = "output.xsd";
   bool gml = false;
   string gml_output = "output.gml";
   string ilidirs = "";
   bool log_silent = false;
   bool log_info = true;
   bool log_warnings = true;
   bool log_errors = true;
   bool log_debug = false;
   string log = "";
   bool gui = false;
   int success_status = 0;

   for (auto arg : arguments.getKeys()) {

      string value = arguments.get(arg);

      if (arg == "help") {
         help = true;
      }
      else if (arg == "usage") {
         usage = true;
      }
      else if (arg == "version") {
         version = true;
      }
      else if (arg == "no_auto") {
         no_auto = true;
      }
      else if (arg == "oIMD") {
         imd = true;
         if (value != "") {
            imd_output = value;
         }
      }
      else if (arg == "o1") {
         ili1 = true;
         if (value != "") {
            ili1_output = value;
         }
      }
      else if (arg == "o23") {
         ili23 = true;
         if (value != "") {
            ili23_output = value;
         }
      }
      else if (arg == "o24") {
         ili24 = true;
         if (value != "") {
            ili24_output = value;
         }
      }
      else if (arg == "oXSD") {
         xsd = true;
         if (value != "") {
            xsd_output = value;
         }
      }
      else if (arg == "oGML") {
         gml = true;
         if (value != "") {
            gml_output = value;
         }
      }
      else if (arg == "output") {
         output = value;
         imd_output = value;
         xsd_output = value;
         gml_output = value;
      }
      else if (arg == "ilidirs") {
         ilidirs = value;
      }
      else if (arg == "repositories" || arg == "models" || arg == "ili-version"
         || arg == "no-default-repositories") {
         // Repository arguments are normalized and validated together below.
      }
      else if (arg == "silent") {
         log_silent = true;
      }
      else if (arg == "no_info") {
         log_info = false;
      }
      else if (arg == "no_warnings") {
         log_warnings = false;
      }
      else if (arg == "no_errors") {
         log_errors = false;
      }
      else if (arg == "debug") {
         log_debug = true;
      }
      else if (arg == "log") {
         log = value;
      }
      else if (arg == "state.modelFilter") {
         state.modelFilter = value;
      }
      else if (arg == "gui") {
         gui = true;
      }
      else if (arg == "success") {
         try {
            success_status = atoi(value.c_str());
         }
         catch (exception e) {
            logger.error("parameter success must be of type int");
         }
      }
      else if (arg == "ident") {
         try {
            logger.setIdentSpaces(atoi(value.c_str()));
         }
         catch (exception e) {
            logger.error("parameter ident must be of type int");
         }
      }
      else if (arg == "werror") {
         logger.warningsAsErrors();
      }
   }

   if (log != "") {
      logger.openFile(log);
   }

   logger.setSilent(log_silent);
   logger.displayInfo(log_info);
   logger.displayWarnings(log_warnings);
   logger.displayErrors(log_errors);
   logger.displayDebug(log_debug);

   if (help) {
      display_help(logger);
      exit(0);
   }
   if (usage) {
      display_usage(logger);
      logger.message("");
      display_examples(logger);
      exit(0);
   }
   if (version) {
      display_version(logger);
      exit(0);
   }
   if (gui) {
      //show_gui();
      exit(0);
   }

#ifdef ILIC_NATIVE_REPOSITORY
   bool has_explicit_ili_files = false;
   for (const auto &arg : arguments.getKeys())
      if (arg.find("ilifile") == 0) has_explicit_ili_files = true;
   const ilic::cli::CliRepositoryConfig repository_config =
      ilic::cli::buildRepositoryConfig(arguments);
   if (auto error = ilic::cli::validateRepositoryCliConfig(
      arguments,repository_config,has_explicit_ili_files)) {
      logger.error(*error);
      return 1;
   }
   std::unique_ptr<ilic::RepositoryManager> repository_manager =
      ilic::cli::createRepositoryManager(repository_config);
#endif

   logger.info(get_version_string());

   logger.info("");
   logger.info("loading ili files from command line ...");
   logger.incNestLevel();
   state.context.files().setAutoSearch(!no_auto);
   vector<string> modelDirectories;
   size_t directoryStart = 0;
   while (directoryStart <= ilidirs.size()) {
      size_t separator = ilidirs.find(';',directoryStart);
      string directory = ilidirs.substr(directoryStart,
         separator == string::npos ? string::npos : separator - directoryStart);
      if (!directory.empty()) modelDirectories.push_back(directory);
      if (separator == string::npos) break;
      directoryStart = separator + 1;
   }
   state.context.files().setModelDirectories(std::move(modelDirectories));
#ifdef ILIC_NATIVE_REPOSITORY
   if (repository_manager && !repository_config.requestedModels.empty()) {
      ilic::RepositoryResult resolved = repository_manager->resolve(
         repository_config.requestedModels,repository_config.schemaLanguage);
      ilic::cli::logRepositoryDiagnostics(logger,resolved.diagnostics);
      if (!resolved.success || !ilic::cli::loadResolvedRepositoryModels(state.context.files(),resolved)) return 1;
   }
#endif
   for (auto arg : arguments.getKeys()) {
      string value = arguments.get(arg);
      if (arg.find("ilifile") == 0) {
         logger.info("loading " + value + " ...");
         logger.incNestLevel();
         if (!state.context.files().loadByFile(value)) {
            logger.info("not done.");
            abort(logger,1);
         }
         logger.decNestLevel();
         logger.info("done.");
      }
   }
   logger.decNestLevel();
   logger.info("done.");

   // get interlis version from last file
   if (state.context.files().files().empty()) {
      logger.error("no input .ili files or root models specified");
      return 1;
   }
   string iliversion = state.context.files().files().back()->getIliVersion();

   logger.info("");
   logger.info("loading imported models ...");
   logger.incNestLevel();
   map<string,bool> loaded_models;
   while (true) {
      int fcount = state.context.files().files().size();
      for (IliFile *f : state.context.files().files()) {
         for (string modelname : f->getRequiredModels()) {
            if (loaded_models[modelname]) {
               continue;
            }
            else if (modelname == "INTERLIS") {
               continue;
            }
            logger.info("searching for model " + modelname + " ...");
            logger.incNestLevel();
            IliFile *f = state.context.files().loadByModel(modelname,iliversion);
#ifdef ILIC_NATIVE_REPOSITORY
            if (f == nullptr && repository_manager) {
               const string schema = !repository_config.schemaLanguage.empty()
                  ? repository_config.schemaLanguage : (iliversion == "1.0" ? "ili1" :
                     (iliversion == "2.4" ? "ili2_4" : "ili2_3"));
               ilic::RepositoryResult resolved = repository_manager->resolve(modelname,schema);
               ilic::cli::logRepositoryDiagnostics(logger,resolved.diagnostics);
               if (resolved.success) {
                  ilic::cli::loadResolvedRepositoryModels(state.context.files(),resolved);
                  f = state.context.files().loadByModel(modelname,iliversion);
               }
            }
#endif
            if (f == nullptr) {
               logger.info("not found.");
               logger.decNestLevel();
               continue;
            }
            loaded_models[modelname] = true;
            logger.decNestLevel();
            logger.info("found in " + f->getFilePath() + ".");
         }
      }
      if (fcount == state.context.files().files().size()) {
         break;
      }
      else if (fcount == 100) {
         // something went wrong
         break;
      }
   }
   logger.decNestLevel();
   logger.info("done.");

   logger.info("");
   logger.info("all input files are:");
   for (IliFile *f : state.context.files().files()) {
      string models = "";
      for (string model : f->getModels()) {
         if (models == "") {
            models = model;
         }
         else {
            models += "," + model;
         }
      }
      if (f->getFilePath() == "INTERLIS") {
         continue;
      }
      if (f->getAutoSearch()) {
         logger.info(1,f->getFilePath() + ", iliversion=" + f->getIliVersion() + ", models=" + models + ", auto search");
      }
      else {
         logger.info(1,f->getFilePath() + ", iliversion=" + f->getIliVersion() + ", models=" + models + ", command line");
      }
   }
   logger.info("done.");

   // compile all .ili files
   bool multiple_iliversions = false;
   compile(state,state.context.files().loadByModel("INTERLIS",iliversion));
   int count=0;
   while (true) {
      bool all_compiled = true;
      for (IliFile *f : state.context.files().files()) {
         if (f->getIliVersion() != iliversion && f->getFilePath() != "INTERLIS") {
            multiple_iliversions = true;
         }
         all_compiled = compile(state,f) && all_compiled;
      }
      if (all_compiled) {
         break;
      }
      count++;
      if (count > 20) {
         logger.info("");
         logger.info("the following files do not compile:");
         for (IliFile *f : state.context.files().files()) {
            if (!compile(state,f)) {
               logger.info("   " + f->getFilePath());
            }
         }
         logger.internal_error("endless compile loop");
      }
   }

   check_model_semantics(state.context.models(),logger);
   check_model_translations(state.context.models(),logger);

   // list all models
   logger.info("");
   logger.info("all models are:");
   for (Model *m : state.context.models().models()) {
      logger.info(1, "model " + m->Name + ", iliversion=" + m->iliVersion + ", file=" + m->_ilifile);
   }
   if (multiple_iliversions) {
      logger.error("multiple iliversions found.");
   }
   logger.info("done.");

   if (logger.getErrorCount() == 0) {
      // generate output
      if (imd) {
         generate_imd(state,imd_output,iliversion);
      }
      if (ili1) {
         Model *m;
         if (state.modelFilter == "") {
            m = state.context.models().models().back();
         }
         else {
            for (auto mm : state.context.models().models()) {
               if (mm->Name == state.modelFilter) {
                  m = mm;
                  break;
               }
            }
         }
         generate_ili1(state,ili1_output,m);
      }
      if (ili23) {
         generate_ili23(state,ili23_output);
      }
      if (ili24) {
         generate_ili24(state,ili24_output);
      }
      if (xsd) {
         generate_xsd(state,xsd_output,iliversion);
      }
      if (gml) {
         generate_gml(state,gml_output,iliversion);
      }
   }
   else if (imd || ili1 || ili23 || ili24 || xsd || gml) {
      logger.info("");
      logger.warning("no output generated, because of errors.");
   }

   logger.info("");
   string message = get_program_name() + " completed with";

   if (logger.getErrorCount() == 0) {
      message += " no errors";
   }
   else if (logger.getErrorCount() == 1) {
      message += " 1 error";
   }
   else {
      message += " " + to_string(logger.getErrorCount()) + " errors";
   }

   if (logger.getWarningCount() == 0) {
      message += ", no warnings";
   }
   else if (logger.getWarningCount() == 1) {
      message += ", 1 warning";
   }
   else {
      message += ", " + to_string(logger.getWarningCount()) + " warnings";
   }

   logger.info(message + ".");
   logger.closeFile();

   if (logger.getErrorCount() == 0) {
      return success_status;
   }
   else {
      return 1;
   }

}
