#include "DiagnosticCode.h"

#include <algorithm>
#include <stdexcept>

namespace util {

namespace {

const std::vector<DiagnosticDefinition> definitions{
   DiagnosticDefinition{DiagnosticId::AbiRequest,"ILIC-ABI-REQUEST"},
   DiagnosticDefinition{DiagnosticId::AssociationDuplicateRole,"ILIC-ASSOCIATION-DUPLICATE-ROLE"},
   DiagnosticDefinition{DiagnosticId::AssociationEndNameMismatch,"ILIC-ASSOCIATION-END-NAME-MISMATCH"},
   DiagnosticDefinition{DiagnosticId::AssociationInvalidBaseKind,"ILIC-ASSOCIATION-INVALID-BASE-KIND"},
   DiagnosticDefinition{DiagnosticId::AssociationAbstractRoleInConcrete,"ILIC-ASSOCIATION-ABSTRACT-ROLE-IN-CONCRETE"},
   DiagnosticDefinition{DiagnosticId::AssociationAdditionalRoleInExtension,"ILIC-ASSOCIATION-ADDITIONAL-ROLE-IN-EXTENSION"},
   DiagnosticDefinition{DiagnosticId::AssociationAggregationBinary,"ILIC-ASSOCIATION-AGGREGATION-BINARY"},
   DiagnosticDefinition{DiagnosticId::AssociationAttributeNameConflict,"ILIC-ASSOCIATION-ATTRIBUTE-NAME-CONFLICT"},
   DiagnosticDefinition{DiagnosticId::AssociationRoleAccessNameConflict,"ILIC-ASSOCIATION-ROLE-ACCESS-NAME-CONFLICT"},
   DiagnosticDefinition{DiagnosticId::AssociationMultipleAggregationRoles,"ILIC-ASSOCIATION-MULTIPLE-AGGREGATION-ROLES"},
   DiagnosticDefinition{DiagnosticId::AssociationMissingEndName,"ILIC-ASSOCIATION-MISSING-END-NAME"},
   DiagnosticDefinition{DiagnosticId::AssociationRoleCount,"ILIC-ASSOCIATION-ROLE-COUNT"},
   DiagnosticDefinition{DiagnosticId::AssociationUnexpectedEndName,"ILIC-ASSOCIATION-UNEXPECTED-END-NAME"},
   DiagnosticDefinition{DiagnosticId::AttributeCardinalityExtension,"ILIC-ATTRIBUTE-CARDINALITY-EXTENSION"},
   DiagnosticDefinition{DiagnosticId::AttributeBaseFinal,"ILIC-ATTRIBUTE-BASE-FINAL"},
   DiagnosticDefinition{DiagnosticId::AttributeBaseNotFound,"ILIC-ATTRIBUTE-BASE-NOT-FOUND"},
   DiagnosticDefinition{DiagnosticId::AttributeExtendedRequired,"ILIC-ATTRIBUTE-EXTENDED-REQUIRED"},
   DiagnosticDefinition{DiagnosticId::AttributeDuplicate,"ILIC-ATTRIBUTE-DUPLICATE"},
   DiagnosticDefinition{DiagnosticId::AttributeExtensionListOrdering,"ILIC-ATTRIBUTE-EXTENSION-LIST-ORDERING"},
   DiagnosticDefinition{DiagnosticId::AttributeExtensionNumericRange,"ILIC-ATTRIBUTE-EXTENSION-NUMERIC-RANGE"},
   DiagnosticDefinition{DiagnosticId::AttributeExtensionStructureTarget,"ILIC-ATTRIBUTE-EXTENSION-STRUCTURE-TARGET"},
   DiagnosticDefinition{DiagnosticId::AttributeExtensionTextKind,"ILIC-ATTRIBUTE-EXTENSION-TEXT-KIND"},
   DiagnosticDefinition{DiagnosticId::AttributeExtensionTextLength,"ILIC-ATTRIBUTE-EXTENSION-TEXT-LENGTH"},
   DiagnosticDefinition{DiagnosticId::AttributeExtensionTransient,"ILIC-ATTRIBUTE-EXTENSION-TRANSIENT"},
   DiagnosticDefinition{DiagnosticId::AttributeIncompatibleExtension,"ILIC-ATTRIBUTE-INCOMPATIBLE-EXTENSION"},
   DiagnosticDefinition{DiagnosticId::AttributeMandatoryExtensionRequired,"ILIC-ATTRIBUTE-MANDATORY-EXTENSION-REQUIRED"},
   DiagnosticDefinition{DiagnosticId::ClassExtendedRequired,"ILIC-CLASS-EXTENDED-REQUIRED"},
   DiagnosticDefinition{DiagnosticId::ClassAbstractInConcreteTopic,"ILIC-CLASS-ABSTRACT-IN-CONCRETE-TOPIC"},
   DiagnosticDefinition{DiagnosticId::ClassAbstractModelContextRequired,"ILIC-CLASS-ABSTRACT-MODEL-CONTEXT-REQUIRED"},
   DiagnosticDefinition{DiagnosticId::ClassSpecializationConflict,"ILIC-CLASS-SPECIALIZATION-CONFLICT"},
   DiagnosticDefinition{DiagnosticId::CompilerInternal,"ILIC-COMPILER-INTERNAL"},
   DiagnosticDefinition{DiagnosticId::CompilerUnsupportedType,"ILIC-COMPILER-UNSUPPORTED-TYPE"},
   DiagnosticDefinition{DiagnosticId::ConstraintDomainTargetUnsupported,"ILIC-CONSTRAINT-DOMAIN-TARGET-UNSUPPORTED"},
   DiagnosticDefinition{DiagnosticId::ConstraintExistenceTypeMismatch,"ILIC-CONSTRAINT-EXISTENCE-TYPE-MISMATCH"},
   DiagnosticDefinition{DiagnosticId::ConstraintGlobalUniqueMultivalueAttribute,"ILIC-CONSTRAINT-GLOBAL-UNIQUE-MULTIVALUE-ATTRIBUTE"},
   DiagnosticDefinition{DiagnosticId::ConstraintGlobalUniqueMultivalueRole,"ILIC-CONSTRAINT-GLOBAL-UNIQUE-MULTIVALUE-ROLE"},
   DiagnosticDefinition{DiagnosticId::ConstraintSetOnStructure,"ILIC-CONSTRAINT-SET-ON-STRUCTURE"},
   DiagnosticDefinition{DiagnosticId::ConstraintUniqueBasketLocal,"ILIC-CONSTRAINT-UNIQUE-BASKET-LOCAL"},
   DiagnosticDefinition{DiagnosticId::EnumerationDuplicateElement,"ILIC-ENUMERATION-DUPLICATE-ELEMENT"},
   DiagnosticDefinition{DiagnosticId::EnumerationExtensionDuplicate,"ILIC-ENUMERATION-EXTENSION-DUPLICATE"},
   DiagnosticDefinition{DiagnosticId::EnumerationValueInvalid,"ILIC-ENUMERATION-VALUE-INVALID"},
   DiagnosticDefinition{DiagnosticId::ExpressionBooleanRequired,"ILIC-EXPRESSION-BOOLEAN-REQUIRED"},
   DiagnosticDefinition{DiagnosticId::ExpressionComparisonTypeMismatch,"ILIC-EXPRESSION-COMPARISON-TYPE-MISMATCH"},
   DiagnosticDefinition{DiagnosticId::ExpressionLogicalRequired,"ILIC-EXPRESSION-LOGICAL-REQUIRED"},
   DiagnosticDefinition{DiagnosticId::ExpressionNumericRequired,"ILIC-EXPRESSION-NUMERIC-REQUIRED"},
   DiagnosticDefinition{DiagnosticId::ExpressionOrderingTypeMismatch,"ILIC-EXPRESSION-ORDERING-TYPE-MISMATCH"},
   DiagnosticDefinition{DiagnosticId::FunctionContractedModelRequired,"ILIC-FUNCTION-CONTRACTED-MODEL-REQUIRED"},
   DiagnosticDefinition{DiagnosticId::FunctionDefinitionArgumentRequired,"ILIC-FUNCTION-DEFINITION-ARGUMENT-REQUIRED"},
   DiagnosticDefinition{DiagnosticId::FunctionCallArgumentCount,"ILIC-FUNCTION-CALL-ARGUMENT-COUNT"},
   DiagnosticDefinition{DiagnosticId::FormatEncoding,"ILIC-FORMAT-ENCODING"},
   DiagnosticDefinition{DiagnosticId::FormatVersion,"ILIC-FORMAT-VERSION"},
   DiagnosticDefinition{DiagnosticId::FunctionSignature,"ILIC-FUNCTION-SIGNATURE"},
   DiagnosticDefinition{DiagnosticId::FunctionArgumentTypeMismatch,"ILIC-FUNCTION-ARGUMENT-TYPE-MISMATCH"},
   DiagnosticDefinition{DiagnosticId::GenericContextConcreteDomainIncompatible,"ILIC-GENERIC-CONTEXT-CONCRETE-DOMAIN-INCOMPATIBLE"},
   DiagnosticDefinition{DiagnosticId::GenericContextDefaultDomainRequired,"ILIC-GENERIC-CONTEXT-DEFAULT-DOMAIN-REQUIRED"},
   DiagnosticDefinition{DiagnosticId::GenericContextImportedDomainExtensionRequired,"ILIC-GENERIC-CONTEXT-IMPORTED-DOMAIN-EXTENSION-REQUIRED"},
   DiagnosticDefinition{DiagnosticId::GenericDeferredCoordinateDomainRequired,"ILIC-GENERIC-DEFERRED-COORDINATE-DOMAIN-REQUIRED"},
   DiagnosticDefinition{DiagnosticId::GenericDeferredContextRequired,"ILIC-GENERIC-DEFERRED-CONTEXT-REQUIRED"},
   DiagnosticDefinition{DiagnosticId::GenericDeferredDomainUnused,"ILIC-GENERIC-DEFERRED-DOMAIN-UNUSED"},
   DiagnosticDefinition{DiagnosticId::GenericDeferredListingRequired,"ILIC-GENERIC-DEFERRED-LISTING-REQUIRED"},
   DiagnosticDefinition{DiagnosticId::GenericCoordRangeMismatch,"ILIC-GENERIC-COORD-RANGE-MISMATCH"},
   DiagnosticDefinition{DiagnosticId::GraphicBaseAlreadyDefined,"ILIC-GRAPHIC-BASE-ALREADY-DEFINED"},
   DiagnosticDefinition{DiagnosticId::InheritanceExtendedAssociationRequired,"ILIC-INHERITANCE-EXTENDED-ASSOCIATION-REQUIRED"},
   DiagnosticDefinition{DiagnosticId::InheritanceExtendedDeclarationRequired,"ILIC-INHERITANCE-EXTENDED-DECLARATION-REQUIRED"},
   DiagnosticDefinition{DiagnosticId::InheritanceExtendedTopicRequired,"ILIC-INHERITANCE-EXTENDED-TOPIC-REQUIRED"},
   DiagnosticDefinition{DiagnosticId::InheritanceFinalBase,"ILIC-INHERITANCE-FINAL-BASE"},
   DiagnosticDefinition{DiagnosticId::InheritanceTargetRequired,"ILIC-INHERITANCE-TARGET-REQUIRED"},
   DiagnosticDefinition{DiagnosticId::InputLoad,"ILIC-INPUT-LOAD"},
   DiagnosticDefinition{DiagnosticId::InputUnsupportedVersion,"ILIC-INPUT-UNSUPPORTED-VERSION"},
   DiagnosticDefinition{DiagnosticId::MetaDangling,"ILIC-META-DANGLING"},
   DiagnosticDefinition{DiagnosticId::MetaSyntax,"ILIC-META-SYNTAX"},
   DiagnosticDefinition{DiagnosticId::MetaTarget,"ILIC-META-TARGET"},
   DiagnosticDefinition{DiagnosticId::MetadataBasketNotFound,"ILIC-METADATA-BASKET-NOT-FOUND"},
   DiagnosticDefinition{DiagnosticId::ModelDependency,"ILIC-MODEL-DEPENDENCY"},
   DiagnosticDefinition{DiagnosticId::ModelImportRequired,"ILIC-MODEL-IMPORT-REQUIRED"},
   DiagnosticDefinition{DiagnosticId::ModelRuntimeParameterDuplicate,"ILIC-MODEL-RUNTIME-PARAMETER-DUPLICATE"},
   DiagnosticDefinition{DiagnosticId::NameAttributeNotFound,"ILIC-NAME-ATTRIBUTE-NOT-FOUND"},
   DiagnosticDefinition{DiagnosticId::NameAmbiguous,"ILIC-NAME-AMBIGUOUS"},
   DiagnosticDefinition{DiagnosticId::NameAssociationNotFound,"ILIC-NAME-ASSOCIATION-NOT-FOUND"},
   DiagnosticDefinition{DiagnosticId::NameClassNotFound,"ILIC-NAME-CLASS-NOT-FOUND"},
   DiagnosticDefinition{DiagnosticId::NameMultipleDeclarations,"ILIC-NAME-MULTIPLE-DECLARATIONS"},
   DiagnosticDefinition{DiagnosticId::NameElementNotFound,"ILIC-NAME-ELEMENT-NOT-FOUND"},
   DiagnosticDefinition{DiagnosticId::NameEndMismatch,"ILIC-NAME-END-MISMATCH"},
   DiagnosticDefinition{DiagnosticId::NameFunctionNotFound,"ILIC-NAME-FUNCTION-NOT-FOUND"},
   DiagnosticDefinition{DiagnosticId::NameLineFormNotFound,"ILIC-NAME-LINE-FORM-NOT-FOUND"},
   DiagnosticDefinition{DiagnosticId::NameModelNotFound,"ILIC-NAME-MODEL-NOT-FOUND"},
   DiagnosticDefinition{DiagnosticId::NameNotFound,"ILIC-NAME-NOT-FOUND"},
   DiagnosticDefinition{DiagnosticId::NamePackageNotFound,"ILIC-NAME-PACKAGE-NOT-FOUND"},
   DiagnosticDefinition{DiagnosticId::NameParameterNotFound,"ILIC-NAME-PARAMETER-NOT-FOUND"},
   DiagnosticDefinition{DiagnosticId::NameRoleNotFound,"ILIC-NAME-ROLE-NOT-FOUND"},
   DiagnosticDefinition{DiagnosticId::NameStructureNotFound,"ILIC-NAME-STRUCTURE-NOT-FOUND"},
   DiagnosticDefinition{DiagnosticId::NameTopicNotFound,"ILIC-NAME-TOPIC-NOT-FOUND"},
   DiagnosticDefinition{DiagnosticId::NameTypeNotFound,"ILIC-NAME-TYPE-NOT-FOUND"},
   DiagnosticDefinition{DiagnosticId::NameUnitNotFound,"ILIC-NAME-UNIT-NOT-FOUND"},
   DiagnosticDefinition{DiagnosticId::NameViewNotFound,"ILIC-NAME-VIEW-NOT-FOUND"},
   DiagnosticDefinition{DiagnosticId::NameViewableNotFound,"ILIC-NAME-VIEWABLE-NOT-FOUND"},
   DiagnosticDefinition{DiagnosticId::NamespaceDuplicateDeclaration,"ILIC-NAMESPACE-DUPLICATE-DECLARATION"},
   DiagnosticDefinition{DiagnosticId::NamespaceInheritedDeclarationConflict,"ILIC-NAMESPACE-INHERITED-DECLARATION-CONFLICT"},
   DiagnosticDefinition{DiagnosticId::NamespaceMemberDuplicate,"ILIC-NAMESPACE-MEMBER-DUPLICATE"},
   DiagnosticDefinition{DiagnosticId::ParseEncoding,"ILIC-PARSE-ENCODING"},
   DiagnosticDefinition{DiagnosticId::ParseSyntax,"ILIC-PARSE-SYNTAX"},
   DiagnosticDefinition{DiagnosticId::PropertyAbstractFinalConflict,"ILIC-PROPERTY-ABSTRACT-FINAL-CONFLICT"},
   DiagnosticDefinition{DiagnosticId::PropertyNotAllowed,"ILIC-PROPERTY-NOT-ALLOWED"},
   DiagnosticDefinition{DiagnosticId::ReferenceAttributeOfClassRequired,"ILIC-REFERENCE-ATTRIBUTE-OF-CLASS-REQUIRED"},
   DiagnosticDefinition{DiagnosticId::ReferenceClassRequired,"ILIC-REFERENCE-CLASS-REQUIRED"},
   DiagnosticDefinition{DiagnosticId::ReferenceClassOrStructureRequired,"ILIC-REFERENCE-CLASS-OR-STRUCTURE-REQUIRED"},
   DiagnosticDefinition{DiagnosticId::ReferenceClassStructureOrAssociationRequired,"ILIC-REFERENCE-CLASS-STRUCTURE-OR-ASSOCIATION-REQUIRED"},
   DiagnosticDefinition{DiagnosticId::ReferenceClassOrAssociationRequired,"ILIC-REFERENCE-CLASS-OR-ASSOCIATION-REQUIRED"},
   DiagnosticDefinition{DiagnosticId::ReferenceClassOrViewRequired,"ILIC-REFERENCE-CLASS-OR-VIEW-REQUIRED"},
   DiagnosticDefinition{DiagnosticId::ReferenceExternalRequired,"ILIC-REFERENCE-EXTERNAL-REQUIRED"},
   DiagnosticDefinition{DiagnosticId::ReferenceParentViewRequired,"ILIC-REFERENCE-PARENT-VIEW-REQUIRED"},
   DiagnosticDefinition{DiagnosticId::ReferenceStructureContextRequired,"ILIC-REFERENCE-STRUCTURE-CONTEXT-REQUIRED"},
   DiagnosticDefinition{DiagnosticId::ReferenceStructureRequired,"ILIC-REFERENCE-STRUCTURE-REQUIRED"},
   DiagnosticDefinition{DiagnosticId::ReferenceTopicRequired,"ILIC-REFERENCE-TOPIC-REQUIRED"},
   DiagnosticDefinition{DiagnosticId::ReferenceViewRequired,"ILIC-REFERENCE-VIEW-REQUIRED"},
   DiagnosticDefinition{DiagnosticId::ReferenceThatAreaViewRequired,"ILIC-REFERENCE-THATAREA-VIEW-REQUIRED"},
   DiagnosticDefinition{DiagnosticId::ReferenceThisAreaViewRequired,"ILIC-REFERENCE-THISAREA-VIEW-REQUIRED"},
   DiagnosticDefinition{DiagnosticId::ReferenceViewableContextRequired,"ILIC-REFERENCE-VIEWABLE-CONTEXT-REQUIRED"},
   DiagnosticDefinition{DiagnosticId::ReferenceAggregatesBaseRequired,"ILIC-REFERENCE-AGGREGATES-BASE-REQUIRED"},
   DiagnosticDefinition{DiagnosticId::ReferencePathElementNameRequired,"ILIC-REFERENCE-PATH-ELEMENT-NAME-REQUIRED"},
   DiagnosticDefinition{DiagnosticId::ReferencePathElementNotFound,"ILIC-REFERENCE-PATH-ELEMENT-NOT-FOUND"},
   DiagnosticDefinition{DiagnosticId::RepositoryCache,"ILIC-REPO-CACHE"},
   DiagnosticDefinition{DiagnosticId::RepositoryChecksum,"ILIC-REPO-CHECKSUM"},
   DiagnosticDefinition{DiagnosticId::RepositoryCycle,"ILIC-REPO-CYCLE"},
   DiagnosticDefinition{DiagnosticId::RepositoryDownload,"ILIC-REPO-DOWNLOAD"},
   DiagnosticDefinition{DiagnosticId::RepositoryIndex,"ILIC-REPO-INDEX"},
   DiagnosticDefinition{DiagnosticId::RepositoryNotFound,"ILIC-REPO-NOT-FOUND"},
   DiagnosticDefinition{DiagnosticId::RepositoryPath,"ILIC-REPO-PATH"},
   DiagnosticDefinition{DiagnosticId::RepositorySite,"ILIC-REPO-SITE"},
   DiagnosticDefinition{DiagnosticId::RepositoryUri,"ILIC-REPO-URI"},
   DiagnosticDefinition{DiagnosticId::RepositoryVersion,"ILIC-REPO-VERSION"},
   DiagnosticDefinition{DiagnosticId::SourceNotFound,"ILIC-SOURCE-NOT-FOUND"},
   DiagnosticDefinition{DiagnosticId::Syntax,"ILIC-SYNTAX"},
   DiagnosticDefinition{DiagnosticId::TranslationCoordDimensionMismatch,"ILIC-TRANSLATION-COORD-DIMENSION-MISMATCH"},
   DiagnosticDefinition{DiagnosticId::TranslationAbstractMismatch,"ILIC-TRANSLATION-ABSTRACT-MISMATCH"},
   DiagnosticDefinition{DiagnosticId::TranslationAttributeMismatch,"ILIC-TRANSLATION-ATTRIBUTE-MISMATCH"},
   DiagnosticDefinition{DiagnosticId::TranslationCardinalityMismatch,"ILIC-TRANSLATION-CARDINALITY-MISMATCH"},
   DiagnosticDefinition{DiagnosticId::TranslationCollectionMismatch,"ILIC-TRANSLATION-COLLECTION-MISMATCH"},
   DiagnosticDefinition{DiagnosticId::TranslationConstraintMismatch,"ILIC-TRANSLATION-CONSTRAINT-MISMATCH"},
   DiagnosticDefinition{DiagnosticId::TranslationDeclarationKindMismatch,"ILIC-TRANSLATION-DECLARATION-KIND-MISMATCH"},
   DiagnosticDefinition{DiagnosticId::TranslationDependencyMismatch,"ILIC-TRANSLATION-DEPENDENCY-MISMATCH"},
   DiagnosticDefinition{DiagnosticId::TranslationDerivedAssociationMismatch,"ILIC-TRANSLATION-DERIVED-ASSOCIATION-MISMATCH"},
   DiagnosticDefinition{DiagnosticId::TranslationDomainReferenceMismatch,"ILIC-TRANSLATION-DOMAIN-REFERENCE-MISMATCH"},
   DiagnosticDefinition{DiagnosticId::TranslationEnumerationMismatch,"ILIC-TRANSLATION-ENUMERATION-MISMATCH"},
   DiagnosticDefinition{DiagnosticId::TranslationEnumFinalMismatch,"ILIC-TRANSLATION-ENUM-FINAL-MISMATCH"},
   DiagnosticDefinition{DiagnosticId::TranslationExpressionMismatch,"ILIC-TRANSLATION-EXPRESSION-MISMATCH"},
   DiagnosticDefinition{DiagnosticId::TranslationExtendedMismatch,"ILIC-TRANSLATION-EXTENDED-MISMATCH"},
   DiagnosticDefinition{DiagnosticId::TranslationExtendsMismatch,"ILIC-TRANSLATION-EXTENDS-MISMATCH"},
   DiagnosticDefinition{DiagnosticId::TranslationFinalMismatch,"ILIC-TRANSLATION-FINAL-MISMATCH"},
   DiagnosticDefinition{DiagnosticId::TranslationFunctionMismatch,"ILIC-TRANSLATION-FUNCTION-MISMATCH"},
   DiagnosticDefinition{DiagnosticId::TranslationGenericMismatch,"ILIC-TRANSLATION-GENERIC-MISMATCH"},
   DiagnosticDefinition{DiagnosticId::TranslationGeometryMismatch,"ILIC-TRANSLATION-GEOMETRY-MISMATCH"},
   DiagnosticDefinition{DiagnosticId::TranslationMetadataMismatch,"ILIC-TRANSLATION-METADATA-MISMATCH"},
   DiagnosticDefinition{DiagnosticId::TranslationModelBaseNotFound,"ILIC-TRANSLATION-MODEL-BASE-NOT-FOUND"},
   DiagnosticDefinition{DiagnosticId::TranslationModelCycle,"ILIC-TRANSLATION-MODEL-CYCLE"},
   DiagnosticDefinition{DiagnosticId::TranslationModelPropertyMismatch,"ILIC-TRANSLATION-MODEL-PROPERTY-MISMATCH"},
   DiagnosticDefinition{DiagnosticId::TranslationModelSelfReference,"ILIC-TRANSLATION-MODEL-SELF-REFERENCE"},
   DiagnosticDefinition{DiagnosticId::TranslationOidMismatch,"ILIC-TRANSLATION-OID-MISMATCH"},
   DiagnosticDefinition{DiagnosticId::TranslationReferenceMismatch,"ILIC-TRANSLATION-REFERENCE-MISMATCH"},
   DiagnosticDefinition{DiagnosticId::TranslationRoleMismatch,"ILIC-TRANSLATION-ROLE-MISMATCH"},
   DiagnosticDefinition{DiagnosticId::TranslationRule,"ILIC-TRANSLATION-RULE"},
   DiagnosticDefinition{DiagnosticId::TranslationTypePropertyMismatch,"ILIC-TRANSLATION-TYPE-PROPERTY-MISMATCH"},
   DiagnosticDefinition{DiagnosticId::TranslationUnitMismatch,"ILIC-TRANSLATION-UNIT-MISMATCH"},
   DiagnosticDefinition{DiagnosticId::TranslationValueMismatch,"ILIC-TRANSLATION-VALUE-MISMATCH"},
   DiagnosticDefinition{DiagnosticId::TranslationViewMismatch,"ILIC-TRANSLATION-VIEW-MISMATCH"},
   DiagnosticDefinition{DiagnosticId::TopicDependencyRequired,"ILIC-TOPIC-DEPENDENCY-REQUIRED"},
   DiagnosticDefinition{DiagnosticId::TypeCoordinateRequired,"ILIC-TYPE-COORDINATE-REQUIRED"},
   DiagnosticDefinition{DiagnosticId::TypeDomainRequired,"ILIC-TYPE-DOMAIN-REQUIRED"},
   DiagnosticDefinition{DiagnosticId::TypeEnumBaseRequired,"ILIC-TYPE-ENUM-BASE-REQUIRED"},
   DiagnosticDefinition{DiagnosticId::TypeFormattedRequired,"ILIC-TYPE-FORMATTED-REQUIRED"},
   DiagnosticDefinition{DiagnosticId::TypeFormattedValueOutOfRange,"ILIC-TYPE-FORMATTED-VALUE-OUT-OF-RANGE"},
   DiagnosticDefinition{DiagnosticId::TypeLineOverlapPrecision,"ILIC-TYPE-LINE-OVERLAP-PRECISION"},
   DiagnosticDefinition{DiagnosticId::RoleCardinalityExtension,"ILIC-ROLE-CARDINALITY-EXTENSION"},
   DiagnosticDefinition{DiagnosticId::RoleBaseFinal,"ILIC-ROLE-BASE-FINAL"},
   DiagnosticDefinition{DiagnosticId::RoleBaseNotFound,"ILIC-ROLE-BASE-NOT-FOUND"},
   DiagnosticDefinition{DiagnosticId::RoleCompositionCardinality,"ILIC-ROLE-COMPOSITION-CARDINALITY"},
   DiagnosticDefinition{DiagnosticId::RoleExtensionStrength,"ILIC-ROLE-EXTENSION-STRENGTH"},
   DiagnosticDefinition{DiagnosticId::RoleExtensionOrdering,"ILIC-ROLE-EXTENSION-ORDERING"},
   DiagnosticDefinition{DiagnosticId::RoleExtensionTarget,"ILIC-ROLE-EXTENSION-TARGET"},
   DiagnosticDefinition{DiagnosticId::RoleNameDuplicate,"ILIC-ROLE-NAME-DUPLICATE"},
   DiagnosticDefinition{DiagnosticId::TransientAttributeFactorRequired,"ILIC-ATTRIBUTE-TRANSIENT-FACTOR-REQUIRED"},
   DiagnosticDefinition{DiagnosticId::ViewAliasNotFound,"ILIC-VIEW-ALIAS-NOT-FOUND"},
   DiagnosticDefinition{DiagnosticId::ViewAttributeInspectionInvalid,"ILIC-VIEW-ATTRIBUTE-INSPECTION-INVALID"},
   DiagnosticDefinition{DiagnosticId::ViewInspectionAttributeNotFound,"ILIC-VIEW-INSPECTION-ATTRIBUTE-NOT-FOUND"},
   DiagnosticDefinition{DiagnosticId::ViewBaseNotFound,"ILIC-VIEW-BASE-NOT-FOUND"},
   DiagnosticDefinition{DiagnosticId::ViewBaseExtensionRequired,"ILIC-VIEW-BASE-EXTENSION-REQUIRED"},
   DiagnosticDefinition{DiagnosticId::ValueMinimumExceedsMaximum,"ILIC-VALUE-MINIMUM-EXCEEDS-MAXIMUM"},
   DiagnosticDefinition{DiagnosticId::ValueRange,"ILIC-VALUE-RANGE"},
   DiagnosticDefinition{DiagnosticId::Warning,"ILIC-WARNING"}
};

}

std::string_view diagnosticCode(DiagnosticId id)
{
   auto found = std::find_if(definitions.begin(),definitions.end(),
      [id](const DiagnosticDefinition &definition) { return definition.id == id; });
   if (found == definitions.end()) {
      throw std::invalid_argument("unknown DiagnosticId");
   }
   return found->code;
}

const std::vector<DiagnosticDefinition> &diagnosticDefinitions()
{
   return definitions;
}

}
